### PR TITLE
Extract ASYNC_PROVIDERS_MAX_EXEC_TIME constant

### PR DESCRIPTION
**Pull request by lisitsyn**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by sabio-yateam** [comment]
Hello.

Please follow the [contribution guide](https://github.com/yandex/metrica-tag/blob/main/CONTRIBUTING.md).

In addition before requesting a review please ensure all [checks that would be performed in CI](https://github.com/yandex/metrica-tag/blob/main/.github/workflows/check-code.yml) are passed.

**Review by sabio-yateam — CHANGES_REQUESTED** [review]
Waiting for fixes and CLA adoption.

**Comment by lisitsyn** [comment]
Just added the CLA agreement.

**Comment by lisitsyn** [comment]
The checks have passed.

**Pull request closed without merging**
